# Podcast Feed Settings
title:          Sermons by David Ollerton
email:          sermons@davidollerton.org
description:    "your-podcast-description"
subtitle:       "your-podcast-subtitle"
url:            http://davidollerton.github.io
lang:           en-GB
author:         David Ollerton
copyright:      "&#x2117; &amp; &#xA9; 2017"
keywords:

# Pagination settings
paginate: 10

# SCSS Output
sass:
  style: :compressed
